##############ALARME#################################################
- id: alarm_armed_away
  alias: '[Alarm] Away Mode Armed'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'armed_away'
  action:
   - service: notify.poliveira_bot
     data:
       message: 'Alarm Away Mode Armed'   
       
- id: alarm_armed_home
  alias: '[Alarm] Home Mode Armed'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'armed_home'
  action:
  - data:
      message: 'Alarm Home Mode Armed'
    service: notify.poliveira_bot

- id: alarm_arming_away
  alias: '[Alarm] Away Mode Arming'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'pending'
  action:
  - data:
      message: 'House alarm activating, ensure all doors and windows are closed'
    service: notify.poliveira_bot

- id: alarm_warning
  alias: '[Alarm] Warning'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'warning'
  action:
  - service: notify.poliveira_bot
    data:
      message: 'ALARM Warning {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][ states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name }}'
      
 #### ALARM TRIGGERED
- id: alarm_triggered
  alias: '[Alarm] Triggered'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'triggered'
  action:
  - delay: '00:00:10'
  - service: xiaomi_aqara.play_ringtone
    data:
      gw_mac: f0:b4:29:cc:1d:83
      ringtone_id: 0
      ringtone_vol: 100
  - service: notify.poliveira_bot
    data:
      message: 'ALARME ACIONADO!!! {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][ states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name }}'
  
  
#Cubo Shake
- alias: Cube event shake_air
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000278d36b_2
      action_type: shake_air
  action:
    - service: light.toggle
      entity_id: light.lampada_wc