homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa Pedro Oliveira
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Lisbon
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  base_url: !secret http_password
  server_port: !secret server_port
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  #ip_ban_enabled: True
  #login_attempts_threshold: 3

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/0uç+
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
   include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
#logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
#tts:
  #- platform: google
 
#logger
logger:

# Cloud
#cloud:
#Alarme
alarm_control_panel: !include alarm.yaml
panel_custom: !include panel_custom.yaml

#group: !include groups.yaml
group: !include_dir_merge_named groups
automation: !include automations.yaml
script: !include scripts.yaml

# Xiaomi You can leave MAC empty if you only have one gateway.
xiaomi_aqara:
   discovery_retry: 5
   gateways:
       - mac: !secret xiaomi_mac
         key: !secret xiaomi_key
         host: !secret xiaomi_ip

#Configurar CAM 1080P
# ffmpeg: ffmpeg_bin: /usr/bin/ffmpeg
# camera:
# - platform: yi
# name: Corredor Cam
# host: '192.168.0.51'
# user: root
# password: ***
# path: /tmp/sd/record
# - platform: local_file 
# file_path: /home/pi/screenshot.png
         
#Example configuration.yaml entry
light:
  - platform: yeelight
    devices:
      192.168.0.56:
        name: Cozinha
      192.168.0.151:
        name: Quarto Crianca         
  - platform: xiaomi_miio
    name: Lampada Entrada
    host: 192.168.0.55
    token: f3f7be7ddb8795e3849f461bd9d51c39
    #token: 8021de8fe7c2366a6b1fb2f91e2a81f3
    model: philips.light.bulb
  - platform: xiaomi_miio
    name: Lampada Wc
    host: 192.168.0.54
    token: d1d260326e671529bc43a3bcf889a778
    model: philips.light.bulb
  - platform: xiaomi_miio
    name: Lampada Sala
    host: 192.168.0.52
    token: 292394575f06276c6ad5270eea2072d5
    model: philips.light.bulb
    
# Consumos Diarios
history_graph:
    graph_daily_consumption:
      name: Consumos Diarios
      entities:
        - switch.plug_158d00010dde01
       # - sensor.plug_power_consumed_kwh
        - sensor.consumption_daily_total_kwh
      hours_to_show: 24
      refresh: 30
      
      
     ## Temperaturas Interiores
    graph_interior_temperature:
      name: Temperaturas Interiores
      entities:
         - sensor.temperature_158d0001ab26e2
         - sensor.temperature_158d0001585314
         - sensor.temperature_158d00011739b9
      hours_to_show: 24
      refresh: 30
      
     ## Temperaturas Interiores
    graph_interior_humidade:
      name: Humidade Interiores
      entities:
         - sensor.humidity_158d0001ab26e2
         - sensor.humidity_158d0001585314
         - sensor.humidity_158d00011739b9
      hours_to_show: 24
      refresh: 30
   
#Configurar Telegram Bot 
telegram_bot:
  - platform: polling
    api_key: 482861509:AAH9fQpdiaENPAGwyjEx-RKTrouofTbxQ7Y
    allowed_chat_ids:
      - 505307658
 
# Notify telegram
notify:
  - name: POliveira_bot
    platform: telegram
    chat_id: 505307658

#Configurar MQTT  
# mqtt:
  # broker: 192.168.0.123
  # port: 1883
  # username: !secret username_mqtt
  # password: !secret password_mqtt
 