###############################################################################
#                                                                             #
#                           G R O U P                                         #
#                                                                             #
###############################################################################
group:
  my_fdsemana:
    name: Fim de Semana
    entities:
      - automation.fimdesemana

###############################################################################
#                                                                             #
#                           A U T O M A T I O N                               #
#                                                                             #
###############################################################################

automation:

#### LIGA LUZES DE PRESENÇA DA BANCADA E MESA DA COZINHA (SAB. E DOM.)
  - alias: 'fim de semana'
    initial_state: false
    trigger:
      - platform: time
        at: '04:00:00'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - sat
    action:
      - service: automation.turn_off
        entity_id: automation.liga_cilindro_as_17h
      - service: automation.turn_off
        entity_id: automation.liga_cilindro_as_06h
      - service: automation.turn_off
        entity_id: automation.liga_desumidificador_humidade_acima_70
      - service: automation.turn_off
        entity_id: automation.liga_aquecedor_temp_down  
      - service: light.turn_off
        entity_id: group.all_lights
      - service: switch.turn_off
        entity_id: group.all_switches
      
#### LIGA LUZES DE PRESENÇA DA BANCADA E MESA DA COZINHA (SAB. E DOM.)
  - alias: 'liga fim de semana'
    initial_state: false
    trigger:
      - platform: time
        at: '16:45:00'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - sun
    action:
      - service: automation.turn_on
        entity_id: automation.liga_cilindro_as_17h
      - service: automation.turn_on
        entity_id: automation.liga_cilindro_as_06h
      - service: automation.turn_on
        entity_id: automation.liga_desumidificador_humidade_acima_70
      - service: automation.turn_on
        entity_id: automation.liga_aquecedor_temp_down        
