homeassistant:

zone:

  - name: home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 50
    icon: mdi:home

  - name: notrabalho
    latitude: !secret latitude_meutrabalho
    longitude: !secret longitude_meutrabalho
    radius: 700
    icon: mdi:airplane

device_tracker:
  
  - platform: mqtt_json
    devices:
     pedro: zanzito/pedro/location
    track_new_devices: True
    interval_seconds: 10
    consider_home: 20
    
sensor:
  
  - platform: mqtt
    state_topic: "zanzito/pedro/battery_level"
    name: "pedro Bateria Telemovel"
    unit_of_measurement: '%'
    #retain: true
    
    
  - platform: template
    sensors:   
      pedro:
        friendly_name: 'Estado pedro'
        value_template: > 
          {%- if is_state('device_tracker.pedro', 'not_home') -%}
           Ausente
          {%- endif -%}
          {%- if is_state('device_tracker.pedro', 'home') -%}
           Em Casa
          {%- endif -%}      
          {%- if is_state('device_tracker.pedro', 'notrabalho') -%} 
           No Trabalho
          {%- endif -%}  

camera:
  
  - name: pedro_cam
    platform: generic
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.pedro.attributes.latitude }},{{ states.device_tracker.pedro.attributes.longitude }}&zoom=16&size=500x500&maptype=roadmap&markers=color:green%7Clabel:JA%7C{{ states.device_tracker.pedro.attributes.latitude }},{{ states.device_tracker.pedro.attributes.longitude }}
    limit_refetch_to_url_change: true  



group:

  zanzito:
    name: Zanzitofamilia
    entities:
      - sensor.pedro
      - sensor.pedro_bateria_telemovel
      #- camera.pedro_cam